dist: trusty
group: edge

language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - TEST_SUITE=unit
  - TEST_SUITE=static

before_install:
  - wget https://gist.githubusercontent.com/gordonknoppe/4b08b39ea14f4c66d750e34af73b6dc9/raw/51b4ffa4080d62a7e0f7ea02eec82ced40534539/auth.json
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist

script:
  # Unit tests
  - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then ./vendor/bin/phpunit -c tests/unit/phpunit.xml.dist; fi"
  # Static tests
  - sh -c "if [ '$TEST_SUITE' = 'static' ]; then ./vendor/bin/phpunit -c tests/static/phpunit.xml.dist; fi"
